### PR TITLE
FIX: only require enum34 on old python versions

### PR DESCRIPTION
**Pull request by tacaswell**
Add CI for 3.6

### CODE REVIEW

**Comment by beregond** [comment]
Nice, I was about to need this myself - thanks :)

**Comment by beregond** [comment]
Fix released in version 2.0.1

**Comment by beregond** [comment]
@tacaswell in fact it doesn't work, please check 2.0.2 - it was fixed there (seems like requirements are rendered statically on build time).

**Comment by tacaswell** [comment]
Ah, poor interaction with universal wheels?  I tend to source install things and/or build conda-packages so I missed that, sorry.

**Comment by beregond** [comment]
No problem :)

**Pull request merged**
